INSERT INTO HEROES (id, name) VALUES (1, 'SPIDERMAN');
INSERT INTO HEROES (id, name) VALUES (2, 'SUPERMAN');
INSERT INTO HEROES (id, name) VALUES (3, 'BATMAN');
INSERT INTO HEROES (id, name) VALUES (4, 'HULL');
INSERT INTO HEROES (id, name) VALUES (5, 'BAD SPENCER');
INSERT INTO HEROES (id, name) VALUES (6, 'ROBIN');
INSERT INTO HEROES (id, name) VALUES (7, 'CAT WOMEN');